services:
  backend:
    container_name: apiforge-backend
    build:
      context: ./ApiForge
      dockerfile: Dockerfile
    ports:
      - "5042:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - apiforge-net

  frontend:
    container_name: apiforge-frontend
    build:
      context: ./WebApp
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://backend:8080
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - apiforge-net

networks:
  apiforge-net:
    driver: bridge